### ISSUE TITLE
Main UI Error Message

### ISSUE THREAD

**Issue by steesdale** [instedd/resourcemap#842] opened 2015-03-26 20:52 UTC
When viewing collections zoomed out there is a error box popping up with no text in it. 

![screen shot 2015-03-26 at 4 51 14 pm](https://cloud.githubusercontent.com/assets/3987608/6856771/80a781aa-d3d8-11e4-9dd7-42f185655480.png)

**Comment by ggiraldez** [comment] 2016-04-11 19:27
Might be related to/duplicate of #853?

**Comment by mmuller** [comment] 2017-04-12 15:27
Duplicate of #853

**Closed** 2017-04-12 15:27 UTC
Labels: bug
